# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_date_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuration Datum', 'verbose_name_plural': 'Configuration Data'},
        ),
    ]
