# Generated by Django 2.0 on 2018-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20170710_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autocomplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name': 'Autocomplete Suggestion',
                'verbose_name_plural': 'Autocomplete Suggestions',
            },
        ),
    ]
